### ISSUE TITLE
Some more info

### ISSUE THREAD

**Issue by michelkamp** [tesla-android/tesla-android.github.io#1]
Hi, Great idea and project. Just wondering why do you need the "Geekworm TC358743XBG HDMI-CSI-2" and how did you manage to control the buttons on the steering wheel ?

Thanks,
michel

**Comment by mikegapinski** [comment]
@michelkamp 

The HDMI interface is used to capture image from the PI in order to stream it to the browser. That is hardware accelerated, meaning that it won't use a lot of resources when the codebase is migrated to be used on a single pi.

In case of the steering wheel controls there are two ways that are supported:
1. Connect Tesla Android directly to the car. Standard steering wheel controls via Bluetooth like with any other Android device
2. CarPlay - the Carlinkit adapter has a mode that allows the audio passthrough to be bypassed. In this instance your iPhone is connected to your Tesla in a standard way and Tesla Android is used only for image for Wireless CarPlay. This method makes CarPlay possible without adding delays/echo to the audio stream.
