### ISSUE TITLE
Autokit app not able to detect the USB accesory / carplay dongle ( Carlinkit CPC200-CCPA) in 2022.38.1 

### ISSUE THREAD

**Issue by shaakirmec** [tesla-android/tesla-android.github.io#42]
Autokit app in Android Pi not able to detect the plugged in USB accesory / carplay dongle ( Carlinkit CPC200-CCPA) in 2022.38.1 (single board version) , but works well in dual board stack version (2022.27.1)

**Comment by bnazari** [comment]
Not sure if this is the solution, but mine wasn't detecting the Carlinkit either, decided to try the EEPROM update using another SD card. It detected it afterwards and works great. Might be worth a shot if you have another SD card around. Use the Raspberry Pi Imager; for Operating System, select "Misc Utility Images" -> Bootloader -> SD Card Boot.

**Comment by paulharman** [comment]
Tried it but unfortunately it didn't help

**Comment by ShodanOne** [comment]
Hi,
Same problem here, even after bootloader update.

**Comment by ShodanOne** [comment]
Hello,
I found a workaround on my side
I noticed that the autokit version installed was an old one compared to the one I have on my dual board version.
Unfortunatly, I was unable to update, since my 4G dongle was not recognized either …
So I connect (with a network cable) the Single Board version to my switch to get an internet connection.
Using an internet browser, I access the Tesla-android frontend and I was able to update Autokit app. Upon the app restart I receive a couple of prompt asking me to allow usb access to Autokit, which I did.
Then the carlinkit dongle was correctly recognized + the Bonus is that now my 4G stick is also recognized !
Now I ready to go with the single board version !

**Comment by paulharman** [comment]
Same here

**Comment by shaakirmec** [comment]
> Hello, I found a workaround on my side I noticed that the autokit version installed was an old one compared to the one I have on my dual board version. Unfortunatly, I was unable to update, since my 4G dongle was not recognized either … So I connect (with a network cable) the Single Board version to my switch to get an internet connection. Using an internet browser, I access the Tesla-android frontend and I was able to update Autokit app. Upon the app restart I receive a couple of prompt asking me to allow usb access to Autokit, which I did. Then the carlinkit dongle was correctly recognized. I still have the issue with my 4G stick not recognized …

Updating the autokit app via the browser in the Androif Pi helped. Did not have to do bootloader update. Closing this issue.

**Comment by notthatpaulyd** [comment]
can someone advise the steps to update auto kit? I never use android and am stumbling through the UI trying to figure it out @shaakirmec @paulharman @ShodanOne

**Comment by paulharman** [comment]
> can someone advise the steps to update auto kit? I never use android and am stumbling through the UI trying to figure it out @shaakirmec @paulharman @ShodanOne

I downloaded the file from here - https://www.carlinkit.com/products_detailed/9257044.html then open it on the pi via the my files app in android.  If you pi has internet I think you can go to settings (cog top left) then right at the bottom is a recheck updates button
